In [946]:
import numpy as np

In [947]:
import pandas as pd

In [948]:
#Getting Started with Python

In [949]:
2 + 3

5

In [950]:
9 - 8

1

In [951]:
6 * 4 

24

In [952]:
8 / 4

2.0

In [953]:
5 / 2

2.5

In [954]:
5 // 2

2

In [955]:
8 + 9 - 10

7

In [956]:
8 + 2 * 3

14

In [957]:
(8 + 2) * 3

30

In [958]:
10 // 3

3

In [959]:
10 / 3

3.3333333333333335

In [960]:
10 % 3

1

In [961]:
'sreypov'

'sreypov'

In [962]:
"sreypov"
print("sreypov")


sreypov


In [963]:
print("Hello world")

Hello world


In [964]:
print('Thank you very much')

Thank you very much


In [965]:
"Hello world"

'Hello world'

In [966]:
print("Sreypov's book")

Sreypov's book


In [967]:
print('Sreypov "book" ')

Sreypov "book" 


In [968]:
print(5 * 'Sreypov')

SreypovSreypovSreypovSreypovSreypov


In [969]:
5 * 'Sreypov'

'SreypovSreypovSreypovSreypovSreypov'

In [970]:
print('c:\docs\sreypov')

c:\docs\sreypov


In [971]:
#Variables in Python 

In [972]:
x = 2
x + 3

5

In [973]:
y = 5
x + y

7

In [974]:
x

2

In [975]:
_  + 10

12

In [976]:
y

5

In [977]:
_ + 10

15

In [978]:
name = 'Sreypov'
name

'Sreypov'

In [979]:
name + ' VAN'

'Sreypov VAN'

In [980]:
name = "YouTube"
name[0]


'Y'

In [981]:
name[-1]

'e'

In [875]:
name[1:4]


'ouT'

In [876]:
a = 'Go '
a + name[1:4]

'Go ouT'

In [877]:
#5_List in Python (here we can group int and string together)

In [7]:
date = [12, 15,23, 30, 4]
date

[12, 15, 23, 30, 4]

In [8]:
date[3]

30

In [9]:
date[2:]

[23, 30, 4]

In [10]:
name = ["Sreypov", "Sokea", 'Lina']
name

['Sreypov', 'Sokea', 'Lina']

In [11]:
Combine = [date, name]
Combine

[[12, 15, 23, 30, 4], ['Sreypov', 'Sokea', 'Lina']]

In [12]:
value = [5.5, 'Sreypov', 20]
value

[5.5, 'Sreypov', 20]

In [13]:
date.append(17)
date

[12, 15, 23, 30, 4, 17]

In [14]:
date.insert(2, 28)
date

[12, 15, 28, 23, 30, 4, 17]

In [15]:
date.remove(28)
date

[12, 15, 23, 30, 4, 17]

In [16]:
date.pop(5)
#in list we thinking about index number

17

In [888]:
date 

[12, 15, 23, 30, 4]

In [889]:
date.extend([1])
date

[12, 15, 23, 30, 4, 1]

In [890]:
min(date)

1

In [891]:
max(date)

30

In [892]:
sum(date)

85

In [893]:
date.sort()
date

[1, 4, 12, 15, 23, 30]

In [894]:
#6_Tuple & Set in Python 

In [17]:
tup = (21, 36, 14, 25)
tup

(21, 36, 14, 25)

In [18]:
tup[2]

14

In [19]:
#we cannot change the value of it. If there is a requirement_that want to set of a value and don't want to change it, so u have to go for a Tuple. 

In [20]:
set = {24, 25, 26, 12, 14}
set

{12, 14, 24, 25, 26}

In [899]:
# Tuple
my_tuple = (1, 2, 3, 2)
print(my_tuple)  # Outputs: (1, 2, 3, 2)

# Set
my_set = {1, 2, 3, 2}
print(my_set)    # Outputs: {1, 2, 3} (Note: Duplicate 2 is removed)


(1, 2, 3, 2)
{1, 2, 3}


In [900]:
##9_More on Variables in Python

In [901]:
num = 5 
id(num)

2190366501296

In [902]:
num = "Sreypov"
id(num)

2188437721264

In [903]:
a = 10
b = a
b

10

In [904]:
id(a)

2190366501456

In [905]:
id(b)

2190366501456

In [906]:
id(10)

2190366501456

In [907]:
c = 10
id(c)

2190366501456

In [908]:
a = 8 
id(a)

2190366501392

In [909]:
c = a
id(c)

2190366501392

In [910]:
##10_Data types

In [911]:
pi = 3.14
pi

3.14

In [912]:
type(pi)

float

In [913]:
num = 7
type(num)

int

In [914]:
num = 6+9j
type(num)

complex

In [915]:
a = 3.6
b = int(a)
type(b)

int

In [916]:
b

3

In [917]:
c = float(b)
c

3.0

In [918]:
type(c)

float

In [919]:
k = 6 
e = complex(b, k)
e

(3+6j)

In [920]:
c<k

True

In [921]:
c>k

False

In [922]:
AB = c<k
AB

True

In [923]:
type(AB)

bool

In [924]:
int(True)

1

In [925]:
int(False)

0

In [926]:
lst =  [25, 36, 45, 12]
type(lst)

list

In [927]:
s = {25, 36, 45, 15, 12, 25}
s 

{12, 15, 25, 36, 45}

In [928]:
type(s)

set

In [929]:
t = (25, 36, 4, 57, 12)
type(t)

tuple

In [930]:
str = "Sreypov"
type(str)

str

In [931]:
range(10)



range(0, 10)

In [932]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [933]:
#a range with different iteration 

In [934]:
list(range(2, 10, 2))

[2, 4, 6, 8]

In [935]:
list(range(3, 10, 4))

[3, 7]

In [936]:
type(range(10))

range

In [937]:
#Dictionary or mapping 

In [938]:
Dict = {"Sreypov":"iPhone","Sokea":"Samsung, iPhone", "Linda":"Mac"}
Dict
# the out put below are called keys

{'Sreypov': 'iPhone', 'Sokea': 'Samsung, iPhone', 'Linda': 'Mac'}

In [939]:
Dict.keys()

dict_keys(['Sreypov', 'Sokea', 'Linda'])

In [940]:
Dict.values()

# the out put below are called value 

dict_values(['iPhone', 'Samsung, iPhone', 'Mac'])

In [941]:
Dict["Sokea"]

#how we get particular value 

'Samsung, iPhone'

In [942]:
Dict.get("Linda")

'Mac'

In [943]:
#11_ Opertors in Python
    

In [13]:
#Arithmetic operator 
x = 2
y = 3
x + y


5

In [3]:
x = x + 2 
x

4

In [4]:
x += 2
x
#insteat of x = x + 2

6

In [5]:
x *= 3
x

18

In [22]:
#Unary Operator

In [26]:
a,b,c = 3, 4, 5
a

3

In [27]:
b

4

In [28]:
n = 7
n

7

In [29]:
-n

-7

In [30]:
    #Relational operator

In [31]:
a < b

True

In [32]:
a > b

False

In [33]:
a == b

False

In [34]:
a = 4 
a==b

True

In [35]:
a>=c

False

In [36]:
#how to say not equal to (!=)
a != c

True

In [37]:
#logical operator 

a = 6
b = 8
a > 4 and b < 9

True

In [27]:
a < 8 and b < 2

False

In [28]:
a < 8 or b < 2

True

In [2]:
x = True
x

True

In [3]:
not x 

False

In [ ]:
#12_Number system conversion in Python 

In [1]:
#to convert from Decimal system to Binary system, using bin
#the out put 0b, b representing binary format 

In [1]:
bin(5)

'0b101'

In [3]:
#to convert the Binary to Decimal just using 0b
0b0101

5

In [4]:
#Decimal to Octal formart using oct
#the out put 0o, o representing octal 
oct(25)


'0o31'

In [5]:
#Decimal to HexaDecimal by using hex
#the out put 0x, x representing HexaDecimal 
hex(25) 

'0x19'

In [ ]:
#13_Swap 2 variables in Python 

In [1]:
a = 5
b = 6 
#put a in a temp variable 

temp = a 
a = b 
b = temp
print(a)
print(b)

6
5


In [3]:
#try in other way
a = 5 
b = 6

a = a + b #11
b = a - b #5
a = a - b #6

print(a)
print(b)

6
5


In [4]:
#try in other way 
a = 5 
b = 6

a = a ^ b
b = a ^ b
a = a ^ b

print(a)
print(b)

6
5


In [6]:
#try in other way 
a = 5 
b = 6

a,b = b,a 
print(a)
print(b)

6
5


In [ ]:
#15_Python BitWise Operators

In [1]:
 #Complement operator or tilde (~) operator
~12

-13

In [3]:
~125

-126

In [4]:
# And (&)
12 & 13  
# bin(12) = 00001100 & bin(13) = 00001101

12

In [5]:
#OR (|) operator
12|13


13

In [6]:
#XOR (^) operator
12 ^ 13

1

In [11]:
#Left shift (<<)
10 << 2

40

In [12]:
#right shift (>>)  
10 >> 2

2

In [ ]:
#16_Import Math in Python

In [14]:
 import math

In [21]:
square_root = math.sqrt(25)  #square root of a number is a value that, when multiplied by itself, gives the original number
square_root

5.0

In [25]:
print(math.floor(2.9))

2


In [28]:
print(math.ceil(2.2)) 
 #2.2 it will get 2 but when applied ceil(up) it got 3

3


In [29]:
3 ** 2

9

In [30]:
print(math.pow(3,2))

9.0


In [31]:
print(math.pi)

3.141592653589793


In [32]:
import math as m
m.sqrt(9)

3.0

In [ ]:
#18_User input in Python 
#how to get the input from a user 

In [4]:
print("Enter your name:")
x = input()
print("Hello, " + x)

Enter your name:
Hello, Sreypov


In [ ]:
#19_If, Elif, Else Statement in Python 


In [7]:
if True:
    print("Im right")
  

Im right


In [13]:
if False:
    print("Im right")
    print("Bye")

In [20]:
x = 4 
r = x % 2

if r==0:
     print("Even")
     if x>5:
         print("Great")
     else:
         print("Not so great")

else:
    print("Odd")

print("Bye")

Even
Not so great
Bye


In [21]:
x = 5

if x==1:
    print("one")

elif(x==2):
    print("Two")

elif(x==3):
    print("Three")

elif(x==4):
    print("Four")

else:
    print("Wrong Input")

Wrong Input


In [ ]:
#20_While loop in Python 

In [24]:
i = 1

while i<=3:
     print("Sreypov")
     i=i+1

Sreypov
Sreypov
Sreypov


In [27]:
i = 3
while i>=1:
    print("Thanks you")
    i = i-1

Thanks you
Thanks you
Thanks you


In [30]:
i = 1

while i<=3:
    print("Sreypov ",end="")
    j=1
    while j<=2:
        print("Sokea ",end="")
        j=j+1

    i=i+1
    print()

Sreypov Sokea Sokea 
Sreypov Sokea Sokea 
Sreypov Sokea Sokea 


In [ ]:
#21_For Loop in Python

In [32]:
x = ["Sreypov",65,2.5]
for i in x:
     print(i)

Sreypov
65
2.5


In [39]:
# let's see the out put style of 2 example below
x = 'Happy'
for i in x:
     print(i)

H
a
p
p
y


In [40]:
for i in ['Happy']:
     print(i)

Happy


In [42]:
for i in range(5):
     print(i)

0
1
2
3
4


In [50]:
for i in range(11,21,2):  # 11start, stop before 21, 2 step to increase  
     print(i)

11
13
15
17
19


In [51]:
for i in range(20,15,-1):
     print(i)

20
19
18
17
16


In [49]:
for i in range(1,21):
    if i%5!=0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


In [ ]:
#22_Break Continue Pass in Python

In [6]:
for i in range(1,20):

    if(i%2!=0):
        pass

    else:
        print(i)

print("ByeBye!")


2
4
6
8
10
12
14
16
18
ByeBye!


In [9]:
for i in range(1,20):

     if i%3==0 and i%5==0:
         continue

     print(i)

print("Bye")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
Bye


In [11]:
av = 5

x = int(input("How many Candies you want?"))

i = 1
while i <= x:

    if i>av:
         print("Out of stock")
         break


    print("Candy")
    i+=1

print("Bye")

Candy
Candy
Candy
Candy
Candy
Out of stock
Bye


In [12]:
#22.1_Break vs Continue vs Pass

for i in range(1,30):

    if(i%2!=0):
        pass

    else:
        print(i)

print("Bye")

2
4
6
8
10
12
14
16
18
20
22
24
26
28
Bye


In [13]:

for i in range(5):

    if i==3:
        break
    print("Hello ",i)

    if i==4:
        pass


def fun():
     pass

a = 5

class Human:
    pass

Hello  0
Hello  1
Hello  2


In [14]:
#23_Printing Patterns in Python

for i in range(4):                              # # # #
    for j in range(4 - i):                      # # #
        print("# ",end="")                      # #
                                                #
    print()

# # # # 
# # # 
# # 
# 


In [15]:
#24_For Else in Python

nums = [10,16,18,21,26]

for num in nums:

    if num % 5 == 0:
        print(num)
        break
else:
    print("not found")

10


In [16]:
#25_Prime Number

num = 10

for i in range(2,num):
    if num % i == 0:
        print("Not Prime")
        break
else:
    print("Prime")

Not Prime


In [51]:
#26_Array in Python

from array import *
vals = array('i',[5,9,8,4,2])
newArr = array(vals.typecode, (a*a for a in vals))

i = 0

while i<len(newArr):
    print(newArr[i])
    i+=1

25
81
64
16
4


In [52]:
#27_Array values from User in Python

from array import *

arr = array('i',[])

n = int(input("Enter the length of the array"))

for i in range(n):
    x = int(input("Enter the next value"))
    arr.append(x)

print(arr)

val = int(input("Enter the value for search"))

k = 0
for e in arr:
    if e==val:
        print(k)
        break

    k+=1

print(arr.index(val))

array('i', [2, 1])
0
0


In [53]:
#28_Why Numpy? Installing Numpy in Pycharm

from numpy import *

arr = array([1,2,3,2,5,4],int)

print(arr)

[1 2 3 2 5 4]


In [5]:
#29_Ways of Creating Arrays in Numpy

from numpy import *

# arr = array([1,2,3,4,5],float)
#
# print(arr.dtype)
# print(arr)

# arr = linspace(0,15)
# arr = arange(1,15,2)

# arr = logspace(1,40,5)
# print('%.2f' %arr[4])

arr = ones(5,int)
print(arr)

[1 1 1 1 1]


In [6]:
#30_Copying an Array

from numpy import *


arr1 = array([2,6,8,1,3])
# arr2 = arr1.view()
arr2 = arr1.copy()

arr1[1] = 7

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 7 8 1 3]
[2 6 8 1 3]
1543070038800
1543195970704


In [7]:
#31_Working with Matrix

from numpy import *
m1 = matrix('1 2 3; 6 4 5;1 6 7')
m2 = matrix('1 2 3; 6 8 5;2 6 7')

m3 = m1 * m2
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]


In [14]:
#32_Functions in Python

def add_sub(x,y):
    c = x+y
    d = x-y
    return c,d

result1,result2 = add_sub(5,4)
print(result1, result2)

9 1


In [9]:
#33_Function Arguments

def update(lst):

    print(id(lst))

    lst[1] = 25
    print(id(lst))
    print("x ", lst)

lst = [10,20,30]
print(id(lst))
update(lst)
print("lst ", lst)

1543195854080
1543195854080
1543195854080
x  [10, 25, 30]
lst  [10, 25, 30]


In [10]:
#34_Types of Arguments

def sum(*b):

   c = 0
   for i in b:
       c = c + i

   print(c)

sum(5,6,34,78)

123


In [11]:
#35_Keyworded Variable Length Arguments

def person(name, **data):
    print(name)
    for i,j in data.items():
        print(i,j)
person('navin',age=28,city='Mumbai',mob=9865432)

navin
age 28
city Mumbai
mob 9865432


In [12]:
#36_Global Keyword in Python

a = 10
print(id(a))

def something():
    a = 9

    x = globals()['a']
    print(id(x))
    print("in fun ",a)

    globals()['a'] = 15



something()

print("outside ",a)

1542989376080
1542989376080
in fun  9
outside  15


In [13]:
#37_Pass List to a Function

def count(lst):

    even = 0
    odd = 0

    for i in  lst:
        if i%2==0:
            even+=1
        else:
            odd+=1

    return even,odd

lst = [20,25,14,19,16,24,28,47,26]

even , odd = count(lst)

print("Even : {} and Odd : {}".format(even,odd))

Even : 6 and Odd : 3


In [14]:
#38_Fibonacci Sequence

def fib(n):

    a = 0
    b = 1

    if n == 1:
        print(a)

    else:
        print(a)
        print(b)

    for i in range(2,n):
        c = a + b
        a = b
        b = c
        print(a+b)

fib(100)

0
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
7540113804746346429


In [15]:
#39_Factorial
def fact(n):

    f = 1

    for i in range(1,n+1):
        f = f * i
    return f


x = 4

result = fact(x)


print(result)

24


In [21]:
#40_Recursion

import sys


n = 2000
sys.setrecursionlimit(n)
print(sys.getrecursionlimit())
def greet(i=0):
    if i < 5:  # Set a limit to the recursion depth
        print("Hello ", i)
        i += 1
        greet(i)

# Call the function
greet()

2000
Hello  0
Hello  1
Hello  2
Hello  3
Hello  4


In [22]:
#41_Factorial using Recursion

def fact(n):

    if(n==0):
        return 1

    return n * fact(n-1)



result = fact(5)

print(result)

120


In [55]:
#42_Anonymous Functions | Lambda

f = lambda a,b : a+b

result = f(5,6)

print(result)

11


In [24]:
#43_Filter Map Reduce

from functools import reduce

nums = [3,2,6,8,4,6,2,9]

evens = list(filter(lambda n : n%2==0,nums))

doubles = list(map(lambda n : n*2,evens))
print(doubles)

sum = reduce(lambda a,b : a+b,doubles)

print(sum)

[4, 12, 16, 8, 12, 4]
56


In [25]:
#44_Decorators

def div(a,b):
    print(a/b)

def smart_div(func):

    def inner(a,b):

        if a<b:
            a,b = b,a
        return func(a,b)

    return inner

div = smart_div(div)

div(2,4)

2.0


In [59]:
#45_Modules
#I've create a module name Calc that stor the math method for Calculate
# def add(a,b):
#     return a+b

# def sub(a,b):
#     return a-b

# def mul(a,b):
#     return a*b

# def div(a,b):
#     return a/b

from Calc import *

a = 9
b = 7

# c = sub(a,b)
c = mul(a,b)

print(c)

63


In [60]:
#46_Special Variable __name__

def main():

    print("Hello")
    print("Welcome User")

if __name__ == "__main__":
    main()

print("Its Time to Calculate")

Hello
Welcome User
Its Time to Calculate


In [62]:
#47_Special Variable __name__ part 2

from Calc_1 import *


def fun1():
    add()
    print("from fun1")

def fun2():
    print("from fun2")

def main():
    fun1()
    fun2()


main()


result 1 is  Calc_1
from fun1
from fun2


In [63]:
#48_Object Oriented Programming
#49_Class and Object

class Computer:

    def config(self):
        print("i5, 16gb, 1TB")

com1 = Computer()
com2 = Computer()


Computer.config(com1)
Computer.config(com2)

com1.config()
com2.config()

i5, 16gb, 1TB
i5, 16gb, 1TB
i5, 16gb, 1TB
i5, 16gb, 1TB


In [65]:
#50__init__ method

class Computer:

    def __init__(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram

    def config(self):
        print("Config is ",self.cpu, self.ram)

com1 = Computer('i5',16)
com2 = Computer('Ryzen 3',8)


com1.config()
com2.config()

Config is  i5 16
Config is  Ryzen 3 8


In [15]:
#51_Constructor, Self and Comparing Objects

class Computer:

    def __init__(self):
        self.name = "Sreypov"
        self.age = 28


    def compare(self,other):
        if self.age == other.age:
            return True
        else:
            return False


c1 = Computer()
c1.age = 30
c2 = Computer()

# c1.name = "Rashi"
# c1.age = 12

if c1.compare(c2):
    print("They are same")
else:
    print("They are different")

# c1.update()

print(c1.name)
print(c2.name)

They are different
Sreypov
Sreypov


In [67]:
#52_Types of Variables

class Car:

    wheels = 4

    def __init__(self):
        self.mil = 10
        self.com = "BMW"


c1 = Car()
c2 = Car()

c1.mil = 8

Car.wheels = 5

print(c1.com , c1.mil , c1.wheels)
print(c2.com , c2.mil , c2.wheels)

BMW 8 5
BMW 10 5


In [68]:
#53_Types of Methods

class Student:

    school = 'Soonchunhyang University'

    def __init__(self,m1,m2,m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self):
        return (self.m1 + self.m2 + self.m3)/3

    @classmethod
    def getSchool(cls):
        return cls.school

    @staticmethod
    def info():
        print("This is Student class.. in abc molude")

s1 = Student(34,47,32)
s2 = Student(89,32,12)



print(s1.avg())
print(Student.getSchool())

Student.info()

37.666666666666664
Soonchunhyang University
This is Student class.. in abc molude


In [16]:
#54_Inner class

class Student:

    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.Laptop()

    def show(self):
        print(self.name , self.rollno)
        self.lap.show()

    class Laptop:

        def __init__(self):
            self.brand = "Hp"
            self.cpu = 'i5'
            self.ram = 8

        def show(self):
            print(self.brand,self.cpu,self.ram)


s1 = Student('Sreypov',2)
s2 = Student('Sokea',3)

s1.show()

lap1 = Student.Laptop()

Sreypov 2
Hp i5 8


In [38]:
#55_Inheritance

class A:
    def feature1(self):
        print("Feature 1 working")

    def feature2(self):
        print("Feature 2 working")

class B:
    def feature3(self):
        print("Feature 3 working")

    def feature4(self):
        print("Feature 4 working")

class C(A,B):
    def feature5(self):
        print("Feature 5 working")


a1 = A()

a1.feature1()
a1.feature2()

b1 = B()

c1 = C()

Feature 1 working
Feature 2 working


In [18]:
#56_Constructor in Inheritance

class A:
    def __init__(self):
        print("in A Init")

    def feature1(self):
        print("Feature 1-A working")

    def feature2(self):
        print("Feature 2 working")

class B:
    def __init__(self):
        # super().__init__()
        print("in B Init")

    def feature3(self):
        print("Feature 1-B working")

    def feature4(self):
        print("Feature 4 working")

class C(A,B):

    def __init__(self):
        super().__init__()
        print("in C init")


    def feat(self):
        super().feature2()
a1 = C()
a1.feat()

in A Init
in C init
Feature 2 working


In [40]:
#58_Duck Typing

class Pycharm:

    def execute(self):
        print("Compiling")
        print("Running")

class MyEditor:
    def execute(self):
        print("Spell Check")
        print("Convention Check")
        print("Compiling")
        print("Running")

class Laptop:

    def code(self,ide):
        ide.execute()

ide = MyEditor()

lap1 = Laptop()
lap1.code(ide)

Spell Check
Convention Check
Compiling
Running


In [ ]:
#59_Operator Overloading | Polymorphism

In [19]:

class Student:

    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2

    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = Student(m1,m2)
        return  s3

    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2:
            return True
        else:
            return False

    def __str__(self):
        return '{} {}'.format( self.m1,self.m2)

s1 = Student(58,69)
s2 = Student(69,65)

s3 = s1 + s2
if s1 > s2:
    print("s1 wins")
else:
    print("s2 wins")

a = 9
print(a.__str__())
print(s2)

s2 wins
9
69 65


In [77]:
#60_Method Overloading and Method Overriding

class Student:

    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2

    def sum(self, a = None, b = None, c = None):
        s = 0
        if a != None and b != None and c != None:
            s = a + b + c
        elif a != None and b != None:
            s = a + b
        else:
            s = a
        return s

s1 = Student(58,69)

print(s1.sum(5,9))

class A:
    def show(self):
        print("In A show")

class B(A):
    pass

s1 = B()
s1.show()

14
In A show


In [86]:
#Abstract Class and Abstract Method

from abc import ABC, abstractmethod
class Computer(ABC):
    @abstractmethod
    def process(self):
        pass


class Laptop(Computer):
    def process(self):
        print("its running")
    pass

class Whiteboard(Computer):
    def write(self):
        print("its writing")

class Programming:
    def work(self, com):
        print("Solving Bugs")
        com.process()
        

# com = Computer()
# com.process()
com1 = Laptop() 
prog1 = Programming()
prog1.work(com1)
com1.process()

Solving Bugs
its running
its running


In [21]:
#61_Iterator


# nums = [7, 8, 9, 5]
# it = iter(nums)
# print(it.__next__())
# # print(it.__next__())
# print(next(it))
# # print(next(it))
# for i in nums:
#     print(i)

class TopTen:
    def __init__(self):
        self.num = 1

    def __iter__(self):
        return self
    def __next__(self):

        if self.num <= 10:
            val = self.num
            self.num +=1

            return val
        else:
            raise StopIteration
        

values = TopTen()
print(next(values))

for i in values:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [99]:
#62_Generator

def topten():
    n = 1

    while n <= 10:

        sq = n*n
        yield sq
        n+=1

value = topten()
for i in value:
    print(i)

1
4
9
16
25
36
49
64
81
100


In [42]:
#63_Exception Handling

a = 5
b = 2

try:
    print("resource Open")
    print(a/b)
    k = int(input("Enter a number"))
    print(k)

except ZeroDivisionError as e:
    print("Hey, You cannot divide a Number by Zero" , e)

except ValueError as e:
    print("Invalid Input")

except Exception as e:
    print("Something went Wrong...")

finally:
    print("resource Closed")

resource Open
2.5
5
resource Closed


In [22]:

#64_MultiThreading


from time import sleep
from threading import *

class Hello(Thread):
    def run(self):
        for i in range(3):
            print("Hello")
            sleep(1)


class Hi(Thread):
    def run(self):
        for i in range(3):
            print("Hi")
            sleep(1)


t1 = Hello()
t2 = Hi()

t1.start()
sleep(0.2)
t2.start()

t1.join()
t2.join()

print("Bye")

Hello
Hi
Hello
Hi
Hello
Hi
Bye


In [4]:
f = open('images/ICT.jpg','rb') # for read image from directory

f1 = open('images/ICT Create new.jpg','wb') # for write image to directory

# for create new an image
for i in f:
    f1.write(i)

In [5]:
#68_Linear Search using Python

pos = -1

def search(list, n):
    i = 0

    while i< len(list):
        if list[i] == n:
            globals()['pos'] = i
            return True
        i = i + 1

    return False

list = [5,8,4,6,9,2]
n = 9

if search(list, n):
    print("Found at ",pos+1)
else:
    print("Not Found")

Found at  5


In [8]:
#69_Binary Search Using Python

pos = -1

def search(list, n):

    l = 0
    u = len(list)-1

    while l <= u:
        mid = (l+u) // 2

        if list[mid] == n:
            globals()['pos'] = mid
            return True
        else:
            if list[mid] < n:
                l = mid+1
            else:
                u = mid-1

    return False


list = [4,7,8,12,45,99,102,702,10987,56666]
n = 12

if search(list, n):
    print("Found at index:",pos+1)
else:
    print("Not Found")

Found at index: 4


In [9]:
#70_Bubble Sort in python | List Sort

def sort(nums):

    for i in range(len(nums)-1,0,-1):
        for j in range(i):
            if nums[j]>nums[j+1]:
                temp = nums[j]
                nums[j] = nums[j+1]
                nums[j+1] = temp


nums = [5, 3, 8, 6, 7, 2]
sort(nums)

print(nums)

[2, 3, 5, 6, 7, 8]


In [10]:
#71_Selection Sort using Python

def sort(nums):

    for i in range(6):
        minpos = i
        for j in range(i,6):
            if nums[j] < nums[minpos]:
                minpos = j


        temp = nums[i]
        nums[i] = nums[minpos]
        nums[minpos] = temp

        print(nums)


nums = [5, 3, 8, 6, 7, 2]
sort(nums)

print(nums)

[2, 3, 8, 6, 7, 5]
[2, 3, 8, 6, 7, 5]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]


In [ ]:
#72_MySQL Workbench Setup | Python Database Connection 
 #connect python with database. need external databas for store the data longer time 
 

In [26]:
#73 Python Database Connection | MySQL

#import libraries
import mysql.connector
from mysql.connector import Error
import pandas as pd

def create_server_connection(host_name, user_name, user_password):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")
    return connection

# put MySQL terminal password (when we installing mysql workbench)
pw = "ictconvergence"

# database name
db = "mysql_python"
connection = create_server_connection("localhost", "root", pw)

MySQL Database connection successful


In [ ]:
#74 Python | Git | VScode | GitHub